#!/usr/bin/env python3
"""Bootstrap installer for Redactortron (Python packages + Poppler).

Run from the repo root::

    python scripts/install_deps.py
    python scripts/install_deps.py --api --dev
    python scripts/install_deps.py --with-poppler   # Windows: download Poppler locally

This is the recommended first-time setup so CLI, Gradio UI, and PDF rendering work.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / ".tools"
POPPLER_DIR = TOOLS / "poppler"
POPPLER_BIN_MARKER = "pdftoppm"


def info(msg: str) -> None:
    print(f"[redactortron] {msg}")


def warn(msg: str) -> None:
    print(f"[redactortron] WARNING: {msg}", file=sys.stderr)


def run(cmd: list[str], *, env: dict[str, str] | None = None) -> None:
    info(" ".join(cmd))
    subprocess.check_call(cmd, cwd=str(ROOT), env=env)


def ensure_python() -> None:
    if sys.version_info < (3, 9):
        raise SystemExit(
            f"Python 3.9+ required; found {sys.version_info.major}.{sys.version_info.minor}"
        )
    info(f"Python {sys.version.split()[0]} ({sys.executable})")


def pip_install(extras: list[str], *, upgrade_pip: bool) -> None:
    py = sys.executable
    if upgrade_pip:
        run([py, "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel"])

    target = "."
    if extras:
        # e.g. .[api,dev]
        target = ".[{0}]".format(",".join(extras))

    run([py, "-m", "pip", "install", "-e", target])


def poppler_on_path() -> bool:
    return shutil.which(POPPLER_BIN_MARKER) is not None or shutil.which(
        f"{POPPLER_BIN_MARKER}.exe"
    ) is not None


def find_local_poppler_bin() -> Path | None:
    if not POPPLER_DIR.exists():
        return None
    for candidate in POPPLER_DIR.rglob("pdftoppm.exe"):
        return candidate.parent
    for candidate in POPPLER_DIR.rglob("pdftoppm"):
        return candidate.parent
    return None


def write_env_file(poppler_bin: Path) -> Path:
    env_path = ROOT / ".env.redactortron"
    # PATH prepend for helpers that source this file
    content = (
        f"# Generated by scripts/install_deps.py — do not commit secrets here.\n"
        f"REDACTORTRON_POPPLER_PATH={poppler_bin}\n"
        f"PATH={poppler_bin}{os.pathsep}%PATH%\n"
        if platform.system() == "Windows"
        else (
            f"# Generated by scripts/install_deps.py\n"
            f"REDACTORTRON_POPPLER_PATH={poppler_bin}\n"
            f"export PATH=\"{poppler_bin}:$PATH\"\n"
        )
    )
    env_path.write_text(content, encoding="utf-8")
    info(f"Wrote {env_path}")
    return env_path


def install_poppler_windows() -> Path:
    """Download a Poppler Windows build into .tools/poppler."""
    TOOLS.mkdir(parents=True, exist_ok=True)
    existing = find_local_poppler_bin()
    if existing is not None:
        info(f"Poppler already present at {existing}")
        return existing

    # Pin a known release asset name pattern; fall back to latest API lookup.
    api = "https://api.github.com/repos/oschwartz10612/poppler-windows/releases/latest"
    info(f"Fetching Poppler release metadata: {api}")
    with urllib.request.urlopen(api, timeout=60) as resp:
        release = json.loads(resp.read().decode("utf-8"))

    asset = None
    for item in release.get("assets", []):
        name = item.get("name", "")
        if name.endswith(".zip") and "Release" in name:
            asset = item
            break
    if asset is None:
        for item in release.get("assets", []):
            if str(item.get("name", "")).endswith(".zip"):
                asset = item
                break
    if asset is None:
        raise RuntimeError("Could not find a Poppler zip asset on GitHub releases.")

    url = asset["browser_download_url"]
    zip_path = TOOLS / asset["name"]
    info(f"Downloading {url}")
    urllib.request.urlretrieve(url, zip_path)

    if POPPLER_DIR.exists():
        shutil.rmtree(POPPLER_DIR)
    POPPLER_DIR.mkdir(parents=True, exist_ok=True)
    info(f"Extracting to {POPPLER_DIR}")
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(POPPLER_DIR)
    zip_path.unlink(missing_ok=True)

    bin_dir = find_local_poppler_bin()
    if bin_dir is None:
        raise RuntimeError("Poppler extracted but pdftoppm.exe was not found.")
    write_env_file(bin_dir)
    info(
        "Poppler installed locally. The app will auto-detect "
        f"REDACTORTRON_POPPLER_PATH / {bin_dir}"
    )
    info(
        "Optional: add this folder permanently to your user PATH:\n"
        f"  {bin_dir}"
    )
    return bin_dir


def install_poppler_hint_unix() -> None:
    system = platform.system()
    if system == "Darwin":
        warn("Install Poppler with: brew install poppler")
    else:
        warn("Install Poppler with: sudo apt-get install -y poppler-utils")
        warn("  (or your distro's poppler package)")


def verify_imports() -> None:
    info("Verifying Python imports…")
    modules = [
        "cv2",
        "numpy",
        "PIL",
        "pdf2image",
        "questionary",
        "rich",
        "gradio",
        "redactortron",
    ]
    failed: list[str] = []
    for name in modules:
        try:
            __import__(name)
            info(f"  OK  {name}")
        except Exception as exc:  # noqa: BLE001
            failed.append(f"{name}: {exc}")
            warn(f"  FAIL {name}: {exc}")
    if failed:
        raise SystemExit("Dependency verification failed:\n  - " + "\n  - ".join(failed))


def fetch_models() -> None:
    """Pre-download the docTR OCR and GLiNER weights into the local cache.

    Doing this at install time (with internet) means the first scan works
    offline and any download problem shows up HERE, in the console, instead
    of killing the web server mid-request ("Failed to fetch" in the browser).
    """
    info("Pre-downloading AI models (docTR OCR + GLiNER). This can take a while…")
    try:
        from doctr.models import ocr_predictor

        info("  Loading docTR OCR predictor…")
        ocr_predictor(pretrained=True)
        info("  OK  docTR OCR weights cached")
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(
            f"Failed to download the docTR OCR model: {exc}\n"
            "Check your internet connection / proxy and rerun setup."
        )

    try:
        from gliner import GLiNER

        model_name = "urchade/gliner_multi_pii-v1"
        info(f"  Loading GLiNER model {model_name}…")
        GLiNER.from_pretrained(model_name)
        info("  OK  GLiNER weights cached")
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(
            f"Failed to download the GLiNER model: {exc}\n"
            "Check your internet connection / proxy and rerun setup."
        )
    info("All models cached — the app can now scan without internet.")


def verify_poppler() -> None:
    local = find_local_poppler_bin()
    if local is not None:
        os.environ["PATH"] = str(local) + os.pathsep + os.environ.get("PATH", "")
        os.environ["REDACTORTRON_POPPLER_PATH"] = str(local)
    if poppler_on_path():
        info(f"Poppler OK ({shutil.which(POPPLER_BIN_MARKER) or shutil.which(POPPLER_BIN_MARKER + '.exe')})")
    else:
        warn("Poppler not found on PATH — PDF scans will fail until it is installed.")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Install Redactortron and system helpers.")
    p.add_argument("--api", action="store_true", help="Include FastAPI extras.")
    p.add_argument("--dev", action="store_true", help="Include pytest/dev extras.")
    p.add_argument(
        "--with-poppler",
        action="store_true",
        help="On Windows, download Poppler into .tools/poppler.",
    )
    p.add_argument(
        "--no-upgrade-pip",
        action="store_true",
        help="Skip upgrading pip/setuptools/wheel.",
    )
    p.add_argument(
        "--skip-verify",
        action="store_true",
        help="Skip import / Poppler checks.",
    )
    p.add_argument(
        "--fetch-models",
        action="store_true",
        help="Pre-download docTR + GLiNER weights so first scan works offline.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    ensure_python()

    extras: list[str] = []
    if args.api:
        extras.append("api")
    if args.dev:
        extras.append("dev")

    info(f"Installing Redactortron from {ROOT}")
    pip_install(extras, upgrade_pip=not args.no_upgrade_pip)

    if platform.system() == "Windows" and (args.with_poppler or not poppler_on_path()):
        if args.with_poppler or not poppler_on_path():
            try:
                if not poppler_on_path() or args.with_poppler:
                    info("Ensuring Poppler (required for PDF rendering)…")
                    install_poppler_windows()
            except Exception as exc:  # noqa: BLE001
                warn(f"Automatic Poppler install failed: {exc}")
                warn(
                    "Manual install: https://github.com/oschwartz10612/poppler-windows/releases"
                )
    elif platform.system() != "Windows" and not poppler_on_path():
        install_poppler_hint_unix()

    if not args.skip_verify:
        verify_imports()
        verify_poppler()

    if args.fetch_models:
        fetch_models()

    info("Done.")
    info("Start the GUI with:")
    info("  python -m redactortron ui")
    info("  (or) python -m redactortron.webui")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
